// src/curriculo.js

const conteudos = {
    "Frente 1": [
        "aspectos qualitativos e quantitativos",
        "transformacoes quimicas",
        "quantidades e unidades",
        "balanceamento de equacoes",
        "estequiometria",
        "teoria cinetica",
        "leis dos gases",
        "equacao de clapeyron",
        "lei de dalton",
        "amagat e graham"
    ],
    "Frente 2": [
        "propriedades da materia",
        "fases da materia",
        "separacao de misturas",
        "modelos atomicos",
        "particulas subatomicas",
        "radioatividade",
        "modelo de rutherford",
        "configuracao eletronica",
        "subniveis e orbitais",
        "tabela periodica",
        "propriedades periodicas",
        "ligacoes quimicas",
        "ligacoes ionicas",
        "ligacoes covalentes",
        "ligacoes metalicas",
        "geometria molecular",
        "interacoes intermoleculares",
        "polaridade de moleculas",
        "oxirreducao",
        "numero de oxidacao",
        "metalurgia",
        "solucoes eletroliticas",
        "comportamento acido base",
        "oxidos",
        "quimica ambiental"
    ],
    "Frente 3": [
        "quimica organica",
        "compostos organicos",
        "atomo de carbono",
        "cadeias carbonicas",
        "grupos funcionais",
        "hidrocarbonetos",
        "petroleo e seus derivados",
        "alifaticos",
        "ciclicos",
        "aromaticos",
        "alcoois",
        "eteres",
        "fenois",
        "aldeidos",
        "cetonas",
        "acidos carboxilicos",
        "esteres",
        "nitrocompostos",
        "aminas",
        "amidas",
        "haletos organicos",
        "tiocompostos",
        "isomeria",
        "reacoes organicas",
        "polimeros sinteticos"
    ],
    "Frente 4": [
        "solucoes aquosas",
        "concentracao das solucoes",
        "diluicao e volumetria",
        "propriedades coligativas",
        "termoquimica",
        "variacao de entalpia",
        "lei de hess",
        "energia de ligacao",
        "entropia e energia livre",
        "cinetica quimica",
        "rapidez das transformacoes",
        "lei cinetica",
        "equilibrio quimico",
        "solucoes tampao",
        "equilibrios de solubilidade",
        "eletroquimica",
        "pilhas e baterias",
        "eletrolise"
    ]
};

module.exports = conteudos;